version: '3'
services:

  # genesis node
  tm-genesis:
    image: watcharaphat/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
    command: 
      - genesis
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-benchmark:${ABCI_PORT:-46000}
    ports:
      - 45000:${TM_RPC_PORT:-45000}
      - 47000:${TM_P2P_PORT:-47000}
    networks:
      - tendermint-benchmark
    depends_on:
      - abci-benchmark
  
  api:
    image: nutthadol/tm-benchmark-api:latest
    environment:
     - TENDERMINT_IP=tm-genesis
     - TENDERMINT_PORT=45000
     - SERVER_PORT=8000
    ports:
      - 8000:8000
    networks:
      - tendermint-benchmark
    depends_on:
      - tm-genesis

  # # secondary nodes
  tm-node:
    image: watcharaphat/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
      - SEED_HOSTNAME=tm-genesis
    command:
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://abci-benchmark:${ABCI_PORT:-46000}
      - --p2p.seeds=tcp://tm-genesis:${TM_P2P_PORT:-47000}
    ports:
      - 45001:${TM_RPC_PORT:-45000}
      - 47001:${TM_P2P_PORT:-47000}
    networks:
      - tendermint-benchmark

  # tm-other-node:
  #   image: watcharaphat/tendermint:latest
  #   environment:
  #     - TM_RPC_PORT=${TM_RPC_PORT:-45000}
  #     - SEED_HOSTNAME=tm-genesis
  #   command:
  #     - secondary
  #     - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
  #     - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
  #     - --proxy_app=tcp://abci-benchmark:${ABCI_PORT:-46000}
  #     - --p2p.seeds=tcp://tm-genesis:${TM_P2P_PORT:-47000}
  #   ports:
  #     - 45002:${TM_RPC_PORT:-45000}
  #     - 47002:${TM_P2P_PORT:-47000}
  #   networks:
  #     - tendermint-benchmark

  # tm-idp:
  #   image: ndidplatform/tendermint:latest
  #   environment:
  #     - SEED_HOSTNAME=tm-ndid
  #     - TM_RPC_PORT=${TM_RPC_PORT:-45000}
  #   command: 
  #     - secondary
  #     - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
  #     - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
  #     - --proxy_app=tcp://abci-idp:${ABCI_PORT:-46000}
  #     - --p2p.seeds=tm-ndid:${TM_P2P_PORT:-47000}
  #   ports:
  #     - 45001:${TM_RPC_PORT:-45000}
  #     - 47001:${TM_P2P_PORT:-47000}
  #   networks:
  #     - ndidplatform
  #   depends_on:
  #     - tm-ndid
  #     - abci-idp
  # tm-rp:
  #   image: ndidplatform/tendermint:latest
  #   environment:
  #     - SEED_HOSTNAME=tm-ndid
  #     - TM_RPC_PORT=${TM_RPC_PORT:-45000}
  #   command: 
  #     - secondary
  #     - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
  #     - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
  #     - --proxy_app=tcp://abci-rp:${ABCI_PORT:-46000}
  #     - --p2p.seeds=tm-ndid:${TM_P2P_PORT:-47000}
  #   ports:
  #     - 45002:${TM_RPC_PORT:-45000}
  #     - 47002:${TM_P2P_PORT:-47000}
  #   networks:
  #     - ndidplatform
  #   depends_on:
  #     - tm-ndid
  #     - abci-rp
  # tm-as:
  #   image: ndidplatform/tendermint:latest
  #   environment:
  #     - SEED_HOSTNAME=tm-ndid
  #     - TM_RPC_PORT=${TM_RPC_PORT:-45000}
  #   command: 
  #     - secondary
  #     - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
  #     - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
  #     - --proxy_app=tcp://abci-as:${ABCI_PORT:-46000}
  #     - --p2p.seeds=tm-ndid:${TM_P2P_PORT:-47000}
  #   ports:
  #     - 45003:${TM_RPC_PORT:-45000}
  #     - 47003:${TM_P2P_PORT:-47000}
  #   networks:
  #     - ndidplatform
  #   depends_on:
  #     - tm-ndid
  #     - abci-as

  # abci containers
  abci-benchmark:
    image: watcharaphat/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    networks:
      - tendermint-benchmark
  # abci-idp:
  #   image: ndidplatform/abci:latest
  #   command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
  #   networks:
  #     - ndidplatform
  # abci-rp:
  #   image: ndidplatform/abci:latest
  #   command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
  #   networks:
  #     - ndidplatform
  # abci-as:
  #   image: ndidplatform/abci:latest
  #   command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
  #   networks:
  #     - ndidplatform

networks:
  tendermint-benchmark: